apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-develop
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: davy.dehaas98@gmail.com
    privateKeySecretRef:
      name: letsencrypt-develop
    solvers:
      - http01:
          ingress:
            class: nginx